delete_vms: false
systems: []
system_to_delete: []
system_to_skip: []
api_url_v3: "https://{{ prism_url }}:9440/api/nutanix/v3"
prism_url: "{{ env }}"
api_url_v1: "https://{{ prism_url }}:9440/PrismGateway/services/rest/v1"
update_prism_admin_str: "dpp/data/nutanix/prism/central:username"
update_prism_password_str: "dpp/data/nutanix/prism/central:password"
initalize: false
overtime: 172800 #set time in seconds 48hrs

