- name: Show specific vm info (no loop)
  ansible.builtin.debug:
    msg:
      #      - "{{ item }}"
      #      - "{{ vm_entities[1].metadata.creation_time }}"
      - "{{ item.metadata.creation_time }} **** {{ item.spec.name }} **** {{ item.metadata.uuid }}"
  tags:
    - never

- name: Get VM creation time
  ansible.builtin.set_fact:
    gettime: "{{ item.metadata.creation_time }}"

- name: Set total time
  ansible.builtin.set_fact:
    totaltime: "{{ (ansible_date_time.iso8601[:19] | to_datetime(fmt) - gettime[:19] | to_datetime(fmt)).total_seconds() }}"
    overtime: false
  vars:
    fmt: "%Y-%m-%dT%H:%M:%S"

- name: Set overtime to true 48 hrs
  ansible.builtin.set_fact:
    overtime: true
  when: totaltime | int > 172800
#  when: totaltime | int > overtime

- name: Over 48 hrs
  ansible.builtin.debug:
    msg:
      - "{{ overtime }} system is over 48 hrs {{ totaltime }} system creation time {{ gettime }}"
  tags:
    - ansible.builtin.debugs
    - never

- name: To be skipped via uuid
  ansible.builtin.debug:
    msg:
      - "{{ item.spec.name }} is SKIPPED"
  when: item.metadata.uuid in skipvmuuid and overtime
  tags:
    - never

- name: To be deleted
  ansible.builtin.debug:
    msg:
      - "{{ item.spec.name }} is #*#*#* DELETED *#*#*#"
  when: item.metadata.uuid not in skipvmuuid and overtime

- name: Ensures VMs are deleted
  ansible.builtin.uri:
    url: "{{ api_url_v3 }}/vms/{{ item.metadata.uuid }}"
    method: DELETE
    validate_certs: false
    status_code: 202
    headers:
      Cookie: "{{ session_cookie }}"
  #  delegate_to: localhost
  when: item.metadata.uuid not in skipvmuuid and overtime and delete_vms

- name: Set fact for system var
  ansible.builtin.set_fact:
    systems: "{{ systems + ['*System name* ' +item.spec.name +' *System UUID* ' +item.metadata.uuid +' *System Creation Time* ' +item.metadata.creation_time] | list }}"

- name: Set fact for system var to be deleted
  ansible.builtin.set_fact:
    system_to_delete: "{{ system_to_delete + ['*System name* ' +item.spec.name +' *System UUID* ' +item.metadata.uuid +' *System Creation Time* ' +item.metadata.creation_time] | list }}"
  when: item.metadata.uuid not in skipvmuuid and overtime

- name: Set fact for system var to be skipped
  ansible.builtin.set_fact:
    system_to_skip: "{{ system_to_skip + ['*System name* ' +item.spec.name +' *System UUID* ' +item.metadata.uuid +' *System Creation Time* ' +item.metadata.creation_time] | list }}"
  when: item.metadata.uuid in skipvmuuid and overtime
